import type { Listing, AreaGuide } from "./catalog";
import type { Agency, Agent, GuideSummary } from "./marketplace";

export const FALLBACK_VERIFIED_LISTINGS: Listing[] = [
  {
    id: "PROP-ISB-001",
    slug: "1-kanal-modern-luxury-villa-dha-phase-2-islamabad",
    title: "1 Kanal Modern Luxury Villa with Landscaped Lawn",
    description: "Exquisite 1 Kanal designer residence in DHA Phase 2 Sector B. Featuring 5 master ensuite bedrooms, double-height foyer, imported Turkish kitchen, Spanish tile accents, private landscaped lawn, and servant quarters. Complete CDA and DHA transfer allotment with zero encumbrances.",
    transaction_type: "sale",
    property_type: "house",
    city: "Islamabad",
    area: "DHA Phase 2",
    price_pkr: 78000000,
    bedrooms: 5,
    bathrooms: 6,
    size_sqft: 4500,
    amenities: ["Private Lawn", "Imported Kitchen", "Smart Home Automation", "Solar Net Metering", "Servant Quarter", "24/7 Gated Security", "CCTV Surveillance"],
    photos: [
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80", alt_text: "Exterior facade with manicured lawn", sort_order: 1 },
      { url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80", alt_text: "Grand living room with double height ceiling", sort_order: 2 },
      { url: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1200&q=80", alt_text: "Gourmet kitchen with island", sort_order: 3 },
    ],
    availability_status: "available",
    availability_confirmed_at: "2026-10-04T12:00:00Z",
    verification: {
      status: "verified",
      reviewed_at: "2026-10-04T10:00:00Z",
      scope: "DHA Allotment and Transfer Title Verified. Physical On-Site Survey Completed.",
      source_url: "https://dhai-r.com.pk/verification",
    },
    publisher: {
      id: "org-premier-estate",
      slug: "premier-capital-estate",
      name: "Premier Capital Estate",
    },
    classification: "luxury_residential",
    sqft_per_marla: 225,
    coordinates: { latitude: 33.5283, longitude: 73.1517 },
  },
  {
    id: "PROP-ISB-002",
    slug: "corner-executive-penthouse-suite-f10-islamabad",
    title: "Corner Executive Penthouse Suite with Margalla Hills View",
    description: "High-floor duplex penthouse in Sector F-10 with breathtaking unobstructed views of the Margalla National Park. 3 expansive bedroom suites, private terrace lounge, central VRF climate control, 100% standby power generator, and 2 dedicated basement parking slots.",
    transaction_type: "rent",
    property_type: "apartment",
    city: "Islamabad",
    area: "F-10",
    price_pkr: 220000,
    bedrooms: 3,
    bathrooms: 3,
    size_sqft: 2800,
    rental_period: "month",
    amenities: ["Margalla Hills View", "Private Terrace", "Central AC", "100% Standby Generator", "2 Underground Parking Slots", "High-speed Passenger Elevators", "Concierge Lobby"],
    photos: [
      { url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80", alt_text: "Penthouse terrace with panoramic Margalla hills vista", sort_order: 1 },
      { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80", alt_text: "Modern open-concept living area with floor to ceiling glass", sort_order: 2 },
    ],
    availability_status: "available",
    availability_confirmed_at: "2026-10-04T12:00:00Z",
    verification: {
      status: "reviewed",
      reviewed_at: "2026-10-04T09:30:00Z",
      scope: "CDA Building Approval and Maintenance Dues Clearance Recorded.",
      source_url: "https://cda.gov.pk/building-control",
    },
    publisher: {
      id: "org-margalla-advisory",
      slug: "margalla-advisory-partners",
      name: "Margalla Advisory Partners",
    },
    classification: "executive_penthouse",
    sqft_per_marla: 225,
    coordinates: { latitude: 33.6938, longitude: 73.0118 },
  },
  {
    id: "PROP-ISB-003",
    slug: "corporate-headquarters-floor-blue-area-islamabad",
    title: "Corporate Headquarters Full Office Floor in Blue Area",
    description: "Entire 8th floor corporate office in a modern Grade-A commercial tower on Jinnah Avenue, Blue Area. Fully fitted with executive boardrooms, open workstations for 60+ staff, high-speed fiber internet, dedicated transformer, and 4 high-speed elevators.",
    transaction_type: "sale",
    property_type: "office",
    city: "Islamabad",
    area: "Blue Area",
    price_pkr: 145000000,
    bedrooms: 0,
    bathrooms: 4,
    size_sqft: 6200,
    amenities: ["Grade-A Commercial Tower", "Jinnah Avenue Frontage", "Executive Boardroom", "High-speed Fiber Connectivity", "Central VRF Air Conditioning", "Dedicated Electric Substation", "Card-Access Security"],
    photos: [
      { url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80", alt_text: "Bright open-concept corporate floor with glass partitioned offices", sort_order: 1 },
      { url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80", alt_text: "Executive conference boardroom overlooking Blue Area", sort_order: 2 },
    ],
    availability_status: "available",
    availability_confirmed_at: "2026-10-04T12:00:00Z",
    verification: {
      status: "verified",
      reviewed_at: "2026-10-04T11:15:00Z",
      scope: "CDA Commercial Registry and Fire Safety Clearance Verified.",
      source_url: "https://cda.gov.pk/commercial-properties",
    },
    publisher: {
      id: "org-premier-estate",
      slug: "premier-capital-estate",
      name: "Premier Capital Estate",
    },
    classification: "corporate_commercial",
    sqft_per_marla: 225,
    coordinates: { latitude: 33.7121, longitude: 73.0642 },
  },
  {
    id: "PROP-ISB-004",
    slug: "designer-agro-farmhouse-gulberg-greens-islamabad",
    title: "4 Kanal Designer Agro-Farmhouse with Private Pool",
    description: "Spectacular 4 Kanal resort-style agro-farmhouse in Gulberg Greens Islamabad. Surrounded by mature fruit orchards, featuring a temperature-controlled swimming pool, outdoor barbecue pavilion, separate guest cottage, and 30kW solar system. Fully gated and secure.",
    transaction_type: "sale",
    property_type: "house",
    city: "Islamabad",
    area: "Gulberg Greens",
    price_pkr: 165000000,
    bedrooms: 6,
    bathrooms: 7,
    size_sqft: 8500,
    amenities: ["Private Swimming Pool", "4 Kanal Landscaped Grounds", "Fruit Orchard", "Guest Villa Annex", "30kW Solar Power System", "Gated Compound", "Underground Electricity"],
    photos: [
      { url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80", alt_text: "Luxurious agro-farmhouse facade with swimming pool and landscaped gardens", sort_order: 1 },
      { url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80", alt_text: "Spacious master bedroom suite opening onto private veranda", sort_order: 2 },
    ],
    availability_status: "available",
    availability_confirmed_at: "2026-10-04T12:00:00Z",
    verification: {
      status: "verified",
      reviewed_at: "2026-10-04T10:45:00Z",
      scope: "IBECHS Gulberg Greens Allotment Registry and NOC Confirmed.",
      source_url: "https://gulberggreens.com/verification",
    },
    publisher: {
      id: "org-premier-estate",
      slug: "premier-capital-estate",
      name: "Premier Capital Estate",
    },
    classification: "luxury_farmhouse",
    sqft_per_marla: 225,
    coordinates: { latitude: 33.5938, longitude: 73.1256 },
  },
  {
    id: "PROP-RAW-001",
    slug: "contemporary-3-bed-luxury-apartment-bahria-town-phase-7",
    title: "Contemporary 3-Bed Luxury Apartment overlooking River View",
    description: "Immaculate 3-bedroom luxury apartment in Bahria Town Phase 7, Rawalpindi. Located in a secure gated complex with direct views of the river promenade. Includes designer Italian kitchen, imported sanitary fittings, private parking, and access to the community clubhouse and gym.",
    transaction_type: "sale",
    property_type: "apartment",
    city: "Rawalpindi",
    area: "Bahria Town Phase 7",
    price_pkr: 38500000,
    bedrooms: 3,
    bathrooms: 3,
    size_sqft: 2200,
    amenities: ["River Promenade View", "Italian Modular Kitchen", "Clubhouse & Gym Access", "Covered Basement Parking", "24/7 Gated Security", "High-speed Elevators", "100% Power Backup"],
    photos: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80", alt_text: "Contemporary sunlit living room with modern minimalist interior", sort_order: 1 },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80", alt_text: "Designer bedroom suite with panoramic window", sort_order: 2 },
    ],
    availability_status: "available",
    availability_confirmed_at: "2026-10-04T12:00:00Z",
    verification: {
      status: "reviewed",
      reviewed_at: "2026-10-04T11:00:00Z",
      scope: "Bahria Town Head Office Record Transfer Scrutiny Recorded.",
      source_url: "https://bahriatown.com/verification",
    },
    publisher: {
      id: "org-bahria-realty",
      slug: "bahria-realty-solutions",
      name: "Bahria Realty Solutions",
    },
    classification: "luxury_apartment",
    sqft_per_marla: 225,
    coordinates: { latitude: 33.5358, longitude: 73.0984 },
  },
  {
    id: "PROP-ISB-005",
    slug: "diplomatic-sector-family-residence-f7-islamabad",
    title: "Prime Sector F-7 Renovated Diplomatic Family Residence",
    description: "Rarely available 2 Kanal classic modern residence in prestigious Sector F-7/2 Islamabad. Complete with 6 ensuite bedrooms, dual formal drawing rooms, teakwood flooring, expansive basement home theater, guard post, and reinforced boundary perimeter.",
    transaction_type: "sale",
    property_type: "house",
    city: "Islamabad",
    area: "F-7",
    price_pkr: 185000000,
    bedrooms: 6,
    bathrooms: 7,
    size_sqft: 9000,
    amenities: ["Prime F-7/2 Address", "2 Kanal Manicured Grounds", "Solid Teakwood Floors", "Home Theater Lounge", "Armed Guard Post & Security Booth", "Reinforced Perimeter", "Staff Quarters (3 Rooms)"],
    photos: [
      { url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80", alt_text: "Grand 2 Kanal F-7 residence exterior with circular driveway", sort_order: 1 },
      { url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80", alt_text: "Formal drawing room with chandelier and expansive garden windows", sort_order: 2 },
    ],
    availability_status: "available",
    availability_confirmed_at: "2026-10-04T12:00:00Z",
    verification: {
      status: "verified",
      reviewed_at: "2026-10-04T11:40:00Z",
      scope: "CDA Estate Management-I Allotment Record & Non-Encumbrance Certificate Scrutinized.",
      source_url: "https://cda.gov.pk/estate-management",
    },
    publisher: {
      id: "org-margalla-advisory",
      slug: "margalla-advisory-partners",
      name: "Margalla Advisory Partners",
    },
    classification: "ultra_luxury_villa",
    sqft_per_marla: 225,
    coordinates: { latitude: 33.7215, longitude: 73.0564 },
  },
];

export const FALLBACK_AGENCIES: Agency[] = [
  {
    id: "org-premier-estate",
    slug: "premier-capital-estate",
    name: "Premier Capital Estate",
    description: "Institutional real estate advisory specializing in prime CDA sectors, DHA Islamabad, and commercial floor investments with comprehensive title clearance.",
    coverage: ["Islamabad Capital", "DHA Phase 2", "Blue Area", "Gulberg Greens", "Sector F-7 / F-8"],
    contact_email: "advisory@premiercapital.pk",
    contact_phone: "+92 51 2801234",
    whatsapp: "+92 300 8551234",
    address: "Level 14, ISE Towers, Jinnah Avenue, Blue Area, Islamabad",
    established: "2008",
    license_number: "CDA-REG/COMM-2024/019",
    approved_at: "2026-09-15T09:00:00Z",
  },
  {
    id: "org-margalla-advisory",
    slug: "margalla-advisory-partners",
    name: "Margalla Advisory Partners",
    description: "Diplomatic and luxury residential brokerage representing high-net-worth individuals and multinational corporate leases across sectors F-6, F-7, F-8, and F-10.",
    coverage: ["Sector F-6 Diplomatic", "Sector F-7 Jinnah Super", "Sector F-10", "Sector E-7", "Islamabad Capital"],
    contact_email: "desk@margallaadvisory.com",
    contact_phone: "+92 51 2654321",
    whatsapp: "+92 333 5223344",
    address: "Suite 402, Executive Heights, Sector F-7 Markaz, Islamabad",
    established: "2012",
    license_number: "CDA-REG/RES-2024/048",
    approved_at: "2026-09-18T10:30:00Z",
  },
  {
    id: "org-bahria-realty",
    slug: "bahria-realty-solutions",
    name: "Bahria Realty Solutions",
    description: "Exclusive representation for luxury riverside apartments, designer villas, and commercial arcades across Bahria Town Phase 1 through 8.",
    coverage: ["Bahria Town Phase 7", "Bahria Phase 8", "River View Promenade", "Rawalpindi"],
    contact_email: "contact@bahriarealty.pk",
    contact_phone: "+92 51 5709876",
    whatsapp: "+92 301 5446677",
    address: "Ground Floor, Civic Center Promenade, Bahria Town Phase 7, Rawalpindi",
    established: "2015",
    license_number: "RDA-REG/CORP-2024/093",
    approved_at: "2026-09-20T11:15:00Z",
  },
];

export const FALLBACK_AGENTS: Agent[] = [
  {
    slug: "malik-tariq-khan",
    name: "Malik Tariq Khan",
    languages: ["English", "Urdu", "Punjabi"],
    agency: FALLBACK_AGENCIES[0],
    title: "Senior Partner & Commercial Transactions Lead",
    bio: "Over 16 years advising institutional funds, corporate enterprises, and high-net-worth diaspora on prime commercial floor acquisitions and DHA Islamabad villas with rigorous CDA/DHA title due diligence.",
    specialties: ["Commercial Towers", "Blue Area Corporate Floors", "DHA Phase 2 Villas", "Title Due Diligence"],
    phone: "+92 300 8551234",
    email: "tariq.khan@premiercapital.pk",
    whatsapp: "+92 300 8551234",
    experience_years: 16,
    license_id: "CDA/ADV-ISB-2018-042",
  },
  {
    slug: "ayesha-farooq",
    name: "Ayesha Farooq",
    languages: ["English", "Urdu"],
    agency: FALLBACK_AGENCIES[0],
    title: "Principal Consultant - Diplomatic & Luxury Residential",
    bio: "Specializing in luxury residential estates, diplomatic family leasing, and Gulberg Greens agro-farmhouse acquisitions. Expert in non-encumbrance verification and expatriate tenancy covenants.",
    specialties: ["Luxury Agro-Farmhouses", "Diplomatic Residences", "Gulberg Greens", "F-7/F-8 Estates"],
    phone: "+92 321 5117890",
    email: "ayesha.farooq@premiercapital.pk",
    whatsapp: "+92 321 5117890",
    experience_years: 11,
    license_id: "CDA/ADV-ISB-2021-118",
  },
  {
    slug: "barrister-zaryab-shah",
    name: "Barrister Zaryab Shah",
    languages: ["English", "Urdu"],
    agency: FALLBACK_AGENCIES[1],
    title: "Senior Legal Counsel & Property Conveyancing Partner",
    bio: "Barrister-at-Law with deep expertise in CDA transfer regulations, inheritance devolution, property tax withholding (Section 7E/236C/K), and high-value freehold conveyancing in Islamabad.",
    specialties: ["Legal Conveyancing", "Tax Withholding (7E/236)", "Inheritance Devolution", "Sector F-6/F-7 Mansions"],
    phone: "+92 333 5223344",
    email: "zaryab.shah@margallaadvisory.com",
    whatsapp: "+92 333 5223344",
    experience_years: 14,
    license_id: "CDA/LEG-ISB-2019-009",
  },
  {
    slug: "daniyal-mir",
    name: "Daniyal Mir",
    languages: ["English", "Urdu", "Pashto"],
    agency: FALLBACK_AGENCIES[1],
    title: "Executive Director - Prime Margalla Enclaves",
    bio: "Focusing on executive penthouses, duplex residences, and prime residential acquisitions across Sectors F-10, F-11, and E-7 with panoramic Margalla National Park vistas.",
    specialties: ["Margalla View Penthouses", "Executive Duplexes", "Sector E-7 Enclaves", "F-10 High-Floor Suites"],
    phone: "+92 345 5334455",
    email: "daniyal.mir@margallaadvisory.com",
    whatsapp: "+92 345 5334455",
    experience_years: 9,
    license_id: "CDA/ADV-ISB-2022-205",
  },
  {
    slug: "usman-chatha",
    name: "Usman Chatha",
    languages: ["English", "Urdu", "Potohari"],
    agency: FALLBACK_AGENCIES[2],
    title: "Managing Director - Bahria & Rawalpindi Territory",
    bio: "12 years orchestrating high-yield riverside residential and commercial arcade investments across Bahria Town Phase 1 through 8, River Promenade, and the Rawalpindi Ring Road corridor.",
    specialties: ["Bahria Town Phase 7/8", "Riverfront Penthouses", "Commercial Arcades", "Rawalpindi Ring Road"],
    phone: "+92 301 5446677",
    email: "usman.chatha@bahriarealty.pk",
    whatsapp: "+92 301 5446677",
    experience_years: 12,
    license_id: "RDA/BR-RAW-2020-077",
  },
];

export const FALLBACK_GUIDE_SUMMARIES: GuideSummary[] = [
  {
    city_slug: "islamabad",
    area_slug: "dha-phase-2",
    title: "DHA Phase 2 & Giga Commercial Corridor",
    reviewed_at: "2026-10-01T10:00:00Z",
  },
  {
    city_slug: "islamabad",
    area_slug: "f-7",
    title: "Sector F-7 & Jinnah Super Enclave",
    reviewed_at: "2026-10-02T11:30:00Z",
  },
  {
    city_slug: "islamabad",
    area_slug: "f-10",
    title: "Sector F-10 & Margalla View Corridor",
    reviewed_at: "2026-10-02T12:00:00Z",
  },
  {
    city_slug: "islamabad",
    area_slug: "gulberg-greens",
    title: "Gulberg Greens Agro Farmhouses",
    reviewed_at: "2026-10-03T09:15:00Z",
  },
  {
    city_slug: "rawalpindi",
    area_slug: "bahria-town-phase-7",
    title: "Bahria Town Phase 7 River Promenade",
    reviewed_at: "2026-10-03T14:45:00Z",
  },
  {
    city_slug: "islamabad",
    area_slug: "blue-area",
    title: "Blue Area Financial & Corporate Boulevard",
    reviewed_at: "2026-10-04T10:30:00Z",
  },
];

export const FALLBACK_AREA_GUIDES: AreaGuide[] = [
  {
    id: "guide-dha-phase-2",
    city_slug: "islamabad",
    area_slug: "dha-phase-2",
    title: "DHA Phase 2 & Giga Commercial Corridor",
    overview_markdown: "DHA Phase 2 is one of the most prominent master-planned gated communities in the twin cities. Strategically located between the GT Road and Islamabad Expressway, it provides exceptional security, underground utilities, and world-class commercial avenues including the World Trade Center Giga Mall.\n\nSectors A through J offer diverse architectural layouts ranging from 10 Marla modern homes to multi-Kanal executive villas.",
    amenities_summary: "WTC Giga Mall, Jacaranda Family Club, Roots Ivy International University, Army Public School, sector parks, and 24/7 dedicated DHA security patrolling.",
    transport_info: "Direct access to Islamabad Expressway (Signal Free Corridor) and GT Road. 25 minutes to Zero Point Islamabad and 35 minutes to Islamabad International Airport.",
    investment_outlook: "High rental demand from corporate executives and multinational consultants. Steady capital appreciation backed by authoritative DHA transfer protocols.",
    reviewed_at: "2026-10-01T10:00:00Z",
    sources: [
      { title: "DHA Islamabad Official Portal", url: "https://dhai-r.com.pk" },
    ],
  },
  {
    id: "guide-f-7",
    city_slug: "islamabad",
    area_slug: "f-7",
    title: "Sector F-7 & Jinnah Super Enclave",
    overview_markdown: "Sector F-7 represents the quintessential diplomatic and heritage luxury of Islamabad. Nestled against the picturesque backdrop of the Margalla Hills, F-7 is celebrated for its wide tree-lined boulevards, quiet residential avenues, and the iconic Jinnah Super Market commercial center.\n\nProperties in F-7 command prime market valuations, offering timeless residential prestige and high foreign diplomatic rental yields.",
    amenities_summary: "Jinnah Super Market (F-7 Markaz), Safa Gold Mall, elite private schools, embassy compounds, high-end international dining, and lush neighborhood greenbelts.",
    transport_info: "Flanked by Faisal Avenue and Seventh Avenue. 5 minutes to Blue Area, 10 minutes to Diplomatic Enclave, and direct connectivity to Margalla Road.",
    investment_outlook: "Top-tier capital preservation asset. Strong sustained demand from embassies, aid missions, and overseas Pakistani executives.",
    reviewed_at: "2026-10-02T11:30:00Z",
    sources: [
      { title: "Capital Development Authority (CDA)", url: "https://cda.gov.pk" },
    ],
  },
  {
    id: "guide-f-10",
    city_slug: "islamabad",
    area_slug: "f-10",
    title: "Sector F-10 & Margalla View Corridor",
    overview_markdown: "Bordered directly by the vast 750-acre Fatima Jinnah Park (F-9), Sector F-10 is a vibrant residential and commercial hub in Islamabad. It offers a balanced urban mix of expansive residential bungalows, modern duplex penthouses, and premier commercial developments like Silver Oaks.\n\nF-10 Markaz is a thriving commercial hub featuring banking headquarters, gourmet eateries, and specialty medical centers.",
    amenities_summary: "Adjacent to Fatima Jinnah (F-9) Park, F-10 Markaz commercial center, Silver Oaks luxury apartments, international banking branches, and fitness clubs.",
    transport_info: "Accessible via Margalla Road, Kashmir Highway, and Nazim-ud-Din Road. Swift commute to G-10 courts, NUST University, and Blue Area.",
    investment_outlook: "Consistent rental yields for luxury apartments and penthouses. High commercial rental value along main Sumbal Road and F-10 Markaz.",
    reviewed_at: "2026-10-02T12:00:00Z",
    sources: [
      { title: "Capital Development Authority (CDA)", url: "https://cda.gov.pk" },
    ],
  },
  {
    id: "guide-gulberg-greens",
    city_slug: "islamabad",
    area_slug: "gulberg-greens",
    title: "Gulberg Greens Agro Farmhouses",
    overview_markdown: "Gulberg Greens (IBECHS) is Islamabad's foremost gated agro-farmhouse destination. Planned around expansive 4, 5, and 10 Kanal parcels, it integrates tranquil countryside living with contemporary urban infrastructure.\n\nCharacterized by 220-foot wide boulevards, dedicated solar street lighting, and scenic water bodies, Gulberg Greens is the preferred haven for designer estate farmhouses.",
    amenities_summary: "Underground electrical grid, civic clubhouse, commercial Civic Center, medical complex, international school campuses, and private security checkpoints.",
    transport_info: "Dedicated interchange directly on Islamabad Expressway. 15 minutes to Blue Area and 20 minutes to Rawalpindi Cantonment.",
    investment_outlook: "Substantial capital growth in agro-residential plots and completed designer farmhouses with high demand for private weekend retreats.",
    reviewed_at: "2026-10-03T09:15:00Z",
    sources: [
      { title: "IBECHS Gulberg Official Administration", url: "https://gulberggreens.com" },
    ],
  },
  {
    id: "guide-bahria-town-phase-7",
    city_slug: "rawalpindi",
    area_slug: "bahria-town-phase-7",
    title: "Bahria Town Phase 7 River Promenade",
    overview_markdown: "Bahria Town Phase 7 is the jewel of Rawalpindi's southern developments. Centered along the Soan River promenade, Phase 7 showcases European-inspired architectural landmarks, riverside cafes, and modern high-rise residential towers.\n\nIt offers self-sufficient infrastructure with independent electrical generation, ensuring an uninterrupted lifestyle for families and executive tenants.",
    amenities_summary: "River View commercial boulevard, Green Valley Premium Hypermarket, Bahria International Hospital, championship golf course access, and community clubhouse.",
    transport_info: "Connected directly via Bahria Expressway to GT Road and DHA Phase 1. 20 minutes to Rawalpindi Saddar.",
    investment_outlook: "High apartment rental yields and steady commercial arcade returns driven by a dense, affluent local consumer demographic.",
    reviewed_at: "2026-10-03T14:45:00Z",
    sources: [
      { title: "Bahria Town Head Office", url: "https://bahriatown.com" },
    ],
  },
  {
    id: "guide-blue-area",
    city_slug: "islamabad",
    area_slug: "blue-area",
    title: "Blue Area Financial & Corporate Boulevard",
    overview_markdown: "Stretching along Jinnah Avenue, Blue Area is the undisputed commercial and financial nexus of Pakistan. It accommodates corporate headquarters, multinational financial institutions, telecom giants, and the Islamabad Stock Exchange.\n\nRecent high-rise approvals have spurred state-of-the-art Grade-A towers featuring modern curtain-wall architecture and underground multi-level parking.",
    amenities_summary: "Grade-A corporate office towers, Metro Bus stations, state banks, international dining, telecommunications centers, and government ministry access.",
    transport_info: "Running through the center of Islamabad along Jinnah Avenue. Direct stops on the Islamabad Metro Bus network connecting Islamabad and Rawalpindi.",
    investment_outlook: "The capital's highest commercial rental yield per square foot. High institutional investor demand for whole office floors and corporate suites.",
    reviewed_at: "2026-10-04T10:30:00Z",
    sources: [
      { title: "Capital Development Authority (CDA)", url: "https://cda.gov.pk" },
    ],
  },
];
